### ISSUE TITLE
rank images

### ISSUE THREAD

**Issue by t3mp0ra** [bugdone/headshotbox#110] opened 2015-12-23 11:15 UTC
![image](https://cloud.githubusercontent.com/assets/16413298/11975482/73b04ce8-a97f-11e5-98e6-9da7d09a5af2.png)

**Comment by clugg** [comment] 2015-12-23 11:31
Duplicate of #105, fixed by clearing your browser's cache.

**Closed** 2015-12-25 13:38 UTC
