### ISSUE TITLE
Demo list not loading

### ISSUE THREAD

**Issue by dasinking** [bugdone/headshotbox#174] opened 2016-07-22 10:54 UTC
When I'm clicking on a player in my player list it shows "Loading" infinitely. Search function works though. 

Log file can be found here: http://pastebin.com/hjyaYvNj

**Comment by bugdone** [comment] 2016-07-22 11:02
Restarting the browser / clearing the cache doesn't fix it?

**Comment by dasinking** [comment] 2016-07-22 11:08
Clearing the cache fixed it temporarily, but it seems to happen again when I'm changing the number of demos per page and then restarting HSBox. Not quite sure though, I'm not able to reproduce the bug 100% of the time.

**Comment by bugdone** [comment] 2016-07-22 11:10
What browser are you using?

**Comment by dasinking** [comment] 2016-07-22 11:12
Chrome v51. Can't seem to reproduce it in Firefox.

**Comment by Rsslone** [comment] 2016-07-23 22:15
Same with me except when I clear cache I can no longer navigate to the player page. It shows the player ID in the URL bar but nothing happens.

**Comment by bugdone** [comment] 2016-07-24 06:14
I can't reproduce the bug at all.
@Rsslone can you please show me the log?

**Comment by Rsslone** [comment] 2016-07-24 07:46
Sure thing. http://pastebin.com/1CvXankE

**Comment by bugdone** [comment] 2016-07-24 09:00
Thanks, managed to reproduce your bug @Rsslone. Didn't think to ask about openid. 
This is a separate issue from the one @dasinking is experiencing though.

**Comment by bugdone** [comment] 2016-07-24 10:50
Try 0.15.1
The opeind bug should be fixed. The other one I couldn't reproduce so I wrote some defensive code for that scenario.

**Closed** 2016-07-28 23:22 UTC
Labels: bug
