### ISSUE TITLE
Feature Request & a question: multiple demos and multiple accounts

### ISSUE THREAD

**Issue by MSVilsen** [bugdone/headshotbox#191] opened 2017-03-13 13:14 UTC
I was wondering if it would be possible to combine the demos of multiple accounts. I have 3 different accounts I play on with my friends, who vary in skill groups, and I would love to have all the accounts and demos combined to see more of my stats. I was also wondering if the banned players tab is still working? I've been receiving messages in-game about players I've reported getting banned, but never seem to find any whatsoever under the banned players section.

**Comment by bugdone** [comment] 2017-03-13 16:42
Duplicate of #24

Regarding the banned players: when you receive in-game messages about banned players you are referring to the Overwatch XP reward popup?

**Comment by MSVilsen** [comment] 2017-03-13 17:10
Yes that as well, but I've also received messages about players I've been queued with receiving VAC bans for example, and it still doesn't show up when I search for bans. Actually I haven't found any whatsoever.

**Comment by bugdone** [comment] 2017-03-13 17:14
Check the log for errors.
The banned tab works for me.

**Comment by MSVilsen** [comment] 2017-03-13 17:51
How do I access the logs?

**Comment by bugdone** [comment] 2017-03-13 20:04
https://github.com/bugdone/headshotbox/wiki/Setup#files

**Comment by MSVilsen** [comment] 2017-03-13 21:51
"17-03-13 17:57:40 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-13 17:57:40 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-13 17:57:40 DESKTOP-UQR5KL1 ERROR [hsbox.core:90] - 
                                          [37mhsbox.core.main[m  [32m                                  [m
                                                      [37m...[m  [32m                                  [m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  46[m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  72[m
                             [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                    jetty.clj: 137[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
                  [37morg.eclipse.jetty.server.Server.doStart[m  [32m                  Server.java: 366[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
         [37morg.eclipse.jetty.server.ServerConnector.doStart[m  [32m         ServerConnector.java: 236[m
[37morg.eclipse.jetty.server.AbstractNetworkConnector.doStart[m  [32mAbstractNetworkConnector.java:  80[m
            [37morg.eclipse.jetty.server.ServerConnector.open[m  [32m         ServerConnector.java: 321[m
                      [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                  [m
                  [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                  [m
                                      [37msun.nio.ch.Net.bind[m  [32m                                   (repeats 2 times)[m
                                     [37msun.nio.ch.Net.bind0[m  [32m                                  [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m
"

This is for today. I've not been able to see VAC bans ever since re-downloading the program

**Comment by bugdone** [comment] 2017-03-13 21:53
If you get this exception then HeadshotBox didn't start. Maybe you have another instance running already?

**Comment by MSVilsen** [comment] 2017-03-13 21:54
> 17-03-09 16:40:49 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-09 16:40:49 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-09 16:40:49 DESKTOP-UQR5KL1 ERROR [hsbox.core:90] - 
                                          [37mhsbox.core.main[m  [32m                                  [m
                                                      [37m...[m  [32m                                  [m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  46[m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  72[m
                             [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                    jetty.clj: 137[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
                  [37morg.eclipse.jetty.server.Server.doStart[m  [32m                  Server.java: 366[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
         [37morg.eclipse.jetty.server.ServerConnector.doStart[m  [32m         ServerConnector.java: 236[m
[37morg.eclipse.jetty.server.AbstractNetworkConnector.doStart[m  [32mAbstractNetworkConnector.java:  80[m
            [37morg.eclipse.jetty.server.ServerConnector.open[m  [32m         ServerConnector.java: 321[m
                      [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                  [m
                  [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                  [m
                                      [37msun.nio.ch.Net.bind[m  [32m                                   (repeats 2 times)[m
                                     [37msun.nio.ch.Net.bind0[m  [32m                                  [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

17-03-09 19:49:15 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197794005186249038_0400630484_183.dem
17-03-09 19:49:15 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197794005186249038_0400630484_183.dem
17-03-09 19:49:20 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197794005186249038_0400630484_183.dem.info
17-03-09 19:49:20 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197794005186249038_0400630484_183.dem
17-03-09 20:45:05 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197800230741344379_0853307277_138.dem
17-03-09 20:45:05 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197800230741344379_0853307277_138.dem
17-03-09 20:45:10 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197800230741344379_0853307277_138.dem.info
17-03-09 20:45:10 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197800230741344379_0853307277_138.dem
17-03-09 21:28:01 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197806774124019777_2053872534_131.dem
17-03-09 21:28:01 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197806774124019777_2053872534_131.dem
17-03-09 21:28:05 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197806774124019777_2053872534_131.dem.info
17-03-09 21:28:05 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197806774124019777_2053872534_131.dem
17-03-10 17:50:53 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-10 17:50:53 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-10 17:50:55 DESKTOP-UQR5KL1 DEBUG [hsbox.version:23] - Latest version 0.16.4
17-03-10 17:50:58 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:104] - Indexer started
17-03-11 00:40:51 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-11 00:40:51 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-11 00:40:52 DESKTOP-UQR5KL1 DEBUG [hsbox.version:23] - Latest version 0.16.4
17-03-11 00:40:56 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:104] - Indexer started
17-03-11 00:40:56 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197975450374635934_1516536890_183.dem
17-03-11 00:40:56 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197975450374635934_1516536890_183.dem
17-03-11 00:40:59 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197975450374635934_1516536890_183.dem.info
17-03-11 00:40:59 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003197975450374635934_1516536890_183.dem
17-03-12 02:31:09 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-12 02:31:09 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-12 02:31:10 DESKTOP-UQR5KL1 DEBUG [hsbox.version:23] - Latest version 0.16.4
17-03-12 02:31:15 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:104] - Indexer started
17-03-12 02:31:15 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198204866052751513_1841565119_134.dem
17-03-12 02:31:15 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198204866052751513_1841565119_134.dem
17-03-12 02:31:18 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198204866052751513_1841565119_134.dem.info
17-03-12 02:31:19 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198204866052751513_1841565119_134.dem
17-03-12 02:31:19 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198179270195151022_1194532120_135.dem
17-03-12 02:31:19 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198179270195151022_1194532120_135.dem
17-03-12 02:31:27 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198179270195151022_1194532120_135.dem.info
17-03-12 02:31:27 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198179270195151022_1194532120_135.dem
17-03-12 02:31:27 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198200648394866883_0424965311_132.dem
17-03-12 02:31:27 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198200648394866883_0424965311_132.dem
17-03-12 02:31:31 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198200648394866883_0424965311_132.dem.info
17-03-12 02:31:31 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198200648394866883_0424965311_132.dem
17-03-12 02:31:32 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198211420172845148_0659128446_135.dem
17-03-12 02:31:32 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198211420172845148_0659128446_135.dem
17-03-12 02:31:36 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198211420172845148_0659128446_135.dem.info
17-03-12 02:31:36 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198211420172845148_0659128446_135.dem
17-03-12 02:31:37 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198186365481124139_0444192988_183.dem
17-03-12 02:31:37 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198186365481124139_0444192988_183.dem
17-03-12 02:31:41 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198186365481124139_0444192988_183.dem.info
17-03-12 02:31:41 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198186365481124139_0444192988_183.dem
17-03-12 02:31:41 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198216531183927417_0594245705_187.dem
17-03-12 02:31:41 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198216531183927417_0594245705_187.dem
17-03-12 02:31:45 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198216531183927417_0594245705_187.dem.info
17-03-12 02:31:45 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198216531183927417_0594245705_187.dem
17-03-13 12:33:26 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-13 12:33:26 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-13 12:33:27 DESKTOP-UQR5KL1 DEBUG [hsbox.version:23] - Latest version 0.16.4
17-03-13 12:33:31 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:104] - Indexer started
17-03-13 12:33:31 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198374678322217121_1350816281_136.dem
17-03-13 12:33:31 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198374678322217121_1350816281_136.dem
17-03-13 12:33:35 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198374678322217121_1350816281_136.dem.info
17-03-13 12:33:35 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198374678322217121_1350816281_136.dem
17-03-13 12:33:36 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198305084819636459_1801577430_138.dem
17-03-13 12:33:36 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198305084819636459_1801577430_138.dem
17-03-13 12:33:43 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198305084819636459_1801577430_138.dem.info
17-03-13 12:33:44 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198305084819636459_1801577430_138.dem
17-03-13 12:33:44 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198382106468155562_0800595495_182.dem
17-03-13 12:33:44 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198382106468155562_0800595495_182.dem
17-03-13 12:33:51 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198382106468155562_0800595495_182.dem.info
17-03-13 12:33:51 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198382106468155562_0800595495_182.dem
17-03-13 12:33:51 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198311613169926352_1144883090_138.dem
17-03-13 12:33:51 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198311613169926352_1144883090_138.dem
17-03-13 12:33:59 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198311613169926352_1144883090_138.dem.info
17-03-13 12:33:59 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198311613169926352_1144883090_138.dem
17-03-13 14:19:45 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198328155236466810_0830110832_187.dem
17-03-13 14:19:45 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198328155236466810_0830110832_187.dem
17-03-13 14:19:50 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198328155236466810_0830110832_187.dem.info
17-03-13 14:19:50 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198328155236466810_0830110832_187.dem
17-03-13 17:04:59 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-13 17:04:59 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-13 17:05:00 DESKTOP-UQR5KL1 DEBUG [hsbox.version:23] - Latest version 0.16.4
17-03-13 17:05:07 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:104] - Indexer started
17-03-13 17:05:07 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198499962518241633_1038911519_185.dem
17-03-13 17:05:07 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198499962518241633_1038911519_185.dem
17-03-13 17:05:12 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198499962518241633_1038911519_185.dem.info
17-03-13 17:05:12 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198499962518241633_1038911519_185.dem
17-03-13 17:05:12 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198504330499981326_1028134606_181.dem
17-03-13 17:05:12 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198504330499981326_1028134606_181.dem
17-03-13 17:05:15 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198504330499981326_1028134606_181.dem.info
17-03-13 17:05:15 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198504330499981326_1028134606_181.dem
17-03-13 17:11:56 DESKTOP-UQR5KL1 DEBUG [hsbox.indexer:68] - Adding path C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198513025661272122_0499445951_186.dem
17-03-13 17:11:56 DESKTOP-UQR5KL1 INFO [hsbox.demo:314] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198513025661272122_0499445951_186.dem
17-03-13 17:12:00 DESKTOP-UQR5KL1 INFO [hsbox.demo:31] - Processing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198513025661272122_0499445951_186.dem.info
17-03-13 17:12:00 DESKTOP-UQR5KL1 DEBUG [hsbox.db:278] - Adding demo data for C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003198513025661272122_0499445951_186.dem
17-03-13 17:57:31 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-13 17:57:31 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-13 17:57:31 DESKTOP-UQR5KL1 INFO [hsbox.core:67] - HeadshotBox 0.16.4  
17-03-13 17:57:31 DESKTOP-UQR5KL1 INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
17-03-13 17:57:31 DESKTOP-UQR5KL1 ERROR [hsbox.core:90] - 
                                          [37mhsbox.core.main[m  [32m                                  [m
                                                      [37m...[m  [32m                                  [m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  46[m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  72[m
                             [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                    jetty.clj: 137[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
                  [37morg.eclipse.jetty.server.Server.doStart[m  [32m                  Server.java: 366[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
         [37morg.eclipse.jetty.server.ServerConnector.doStart[m  [32m         ServerConnector.java: 236[m
[37morg.eclipse.jetty.server.AbstractNetworkConnector.doStart[m  [32mAbstractNetworkConnector.java:  80[m
            [37morg.eclipse.jetty.server.ServerConnector.open[m  [32m         ServerConnector.java: 321[m
                      [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                  [m
                  [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                  [m
                                      [37msun.nio.ch.Net.bind[m  [32m                                   (repeats 2 times)[m
                                     [37msun.nio.ch.Net.bind0[m  [32m                                  [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

17-03-13 17:57:31 DESKTOP-UQR5KL1 ERROR [hsbox.core:90] - 
                                          [37mhsbox.core.main[m  [32m                                  [m
                                                      [37m...[m  [32m                                  [m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  46[m
                                         [33mhsbox.core/[1;33m-main[m  [32m                     core.clj:  72[m
                             [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                    jetty.clj: 137[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
                  [37morg.eclipse.jetty.server.Server.doStart[m  [32m                  Server.java: 366[m
 [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m       AbstractLifeCycle.java:  68[m
         [37morg.eclipse.jetty.server.ServerConnector.doStart[m  [32m         ServerConnector.java: 236[m
[37morg.eclipse.jetty.server.AbstractNetworkConnector.doStart[m  [32mAbstractNetworkConnector.java:  80[m
            [37morg.eclipse.jetty.server.ServerConnector.open[m  [32m         ServerConnector.java: 321[m
                      [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                  [m
                  [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                  [m
                                      [37msun.nio.ch.Net.bind[m  [32m                                   (repeats 2 times)[m
                                     [37msun.nio.ch.Net.bind0[m  [32m                                  [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

>

**Comment by bugdone** [comment] 2017-03-13 22:04
It might be the case that it didn't finish querying the Steam API.
Go to Settings -> Steam API. Check if the Refresh button displays an animation. If it does, then it's querying the Steam API and you need to wait until it finishes. If there's no animation, you can click it to refresh the banned info.

**Closed** 2017-03-23 20:26 UTC
