### ISSUE TITLE
Large rank icon

### ISSUE THREAD

**Issue by kymatica** [bugdone/headshotbox#109] opened 2015-12-22 11:05 UTC
When viewing the scores of a game the rank icons are sometimes quite large and skew the display.

Edit: I'm using Firefox v 43.0.1 on Windows 10 x64.

![ranks](https://cloud.githubusercontent.com/assets/3047130/11953885/f6121eec-a8f7-11e5-83a6-1c609d695917.png)

**Comment by bugdone** [comment] 2015-12-22 11:47
duplicate of #105

**Closed by bugdone** 2015-12-22 11:47 UTC
