### ISSUE TITLE
Filter games by rank

### ISSUE THREAD

**Issue by aborn0922** [bugdone/headshotbox#125] opened 2016-02-15 17:56 UTC
It would be great to be able to filter games by rank. I started in lower ranks than I am now, yet these games are still included in calculating my stats. It would be great if I could filter down to my current rank so that I know my more current statistics overall

**Comment by bugdone** [comment] 2016-02-15 18:55
You could use the date filter for more current stats.

**Comment by bugdone** [comment] 2016-03-02 16:28
Duplicate of #130

**Closed by bugdone** 2016-03-02 16:28 UTC
Labels: enhancement
