### ISSUE TITLE
Can't view my own and some of my friends stats

### ISSUE THREAD

**Issue by adam434** [bugdone/headshotbox#9] opened 2015-05-08 12:03 UTC
In the player list I have me and all my friends. for some users, it shows an empty list, and there is a NullPointerException in console.

Stacktrace:
2015-05-08 13:59:25.395:WARN:oejs.AbstractHttpConnection:/api/player/76561198014368047/demos
java.lang.NullPointerException
        at clojure.lang.Numbers.ops(Numbers.java:961)
        at clojure.lang.Numbers.lte(Numbers.java:223)
        at hsbox.stats$build_clutch_round_fn$fn__7554$fn__7555.invoke(stats.clj:115)
        at clojure.core$filter$fn__4264.invoke(core.clj:2601)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$take_while$fn__4274.invoke(core.clj:2636)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$reduce1.invoke(core.clj:897)
        at clojure.core$reverse.invoke(core.clj:911)
        at hsbox.stats$build_clutch_round_fn$fn__7554.invoke(stats.clj:121)
        at hsbox.stats$update_stats_with_round.invoke(stats.clj:134)
        at clojure.core.protocols$fn__6086.invoke(protocols.clj:143)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at hsbox.stats$update_stats_with_demo.invoke(stats.clj:153)
        at hsbox.stats$stats_for_demo.invoke(stats.clj:182)
        at hsbox.stats$append_demo_stats.invoke(stats.clj:202)
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$map$fn__4245.invoke(core.clj:2551)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$map$fn__4245.invoke(core.clj:2551)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:598)
        at clojure.core$next.invoke(core.clj:64)
        at cheshire.generate$generate.invoke(generate.clj:127)
        at cheshire.core$generate_string.invoke(core.clj:32)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$update_in.doInvoke(core.clj:5698)
        at clojure.lang.RestFn.invoke(RestFn.java:467)
        at ring.middleware.json$wrap_json_response$fn__8410.invoke(json.clj:67)
        at ring.middleware.json$wrap_json_body$fn__8393.invoke(json.clj:35)
        at ring.middleware.cors$wrap_cors$fn__8377.invoke(cors.clj:150)
        at compojure.core$routing$fn__1396.invoke(core.clj:127)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:127)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at hsbox.handler$fn__8456.invoke(handler.clj:66)
        at compojure.core$if_context$fn__1418.invoke(core.clj:198)
        at compojure.core$routing$fn__1396.invoke(core.clj:127)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:127)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:626)
        at compojure.core$routes$fn__1400.invoke(core.clj:132)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1519.invoke(keyword_params.clj:35)
        at ring.middleware.nested_params$wrap_nested_params$fn__1562.invoke(nested_params.clj:84)
        at ring.middleware.params$wrap_params$fn__1492.invoke(params.clj:64)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__1598.invoke(multipart_params.clj:
        at ring.middleware.flash$wrap_flash$fn__2272.invoke(flash.clj:35)
        at ring.middleware.session$wrap_session$fn__2259.invoke(session.clj:98)
        at clojure.lang.Var.invoke(Var.java:379)
        at ring.adapter.jetty$proxy_handler$fn__8518.invoke(jetty.clj:20)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Un
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:48
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:9
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpCo
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)

**Comment by bugdone** [comment] 2015-05-08 17:21
Duplicate of #8

**Closed** 2015-05-08 17:21 UTC
Labels: duplicate
