### ISSUE TITLE
Headshotbox error on launch

### ISSUE THREAD

**Issue by reinZz** [bugdone/headshotbox#89] opened 2015-11-09 07:13 UTC
Previous versions of headshotbox used to work perfectly fine, but after updating to version 0.10.0, this error is shown in the command prompt seconds after running the batch file:

```

C:\Users\FrqnCy\Desktop\hsbox>java -jar hsbox-0.10.0-standalone.jar --port 4000

2015-Nov-09 15:13:13 +0800 FrqnCy-pc INFO [hsbox.core] - HeadshotBox 0.10.0
2015-Nov-09 15:13:13 +0800 FrqnCy-pc INFO [hsbox.version] - Checking latest vers
ion on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windo
ws-version
2015-11-09 15:13:13.933:INFO:oejs.Server:jetty-7.x.y-SNAPSHOT
2015-11-09 15:13:13.992:INFO:oejs.AbstractConnector:Started SelectChannelConnect
or@0.0.0.0:4000
2015-Nov-09 15:13:14 +0800 FrqnCy-pc DEBUG [hsbox.version] - Latest version 0.10
.0
2015-Nov-09 15:13:14 +0800 FrqnCy-pc ERROR [hsbox.core] -
               ←[37mhsbox.core.main←[m  ←[32m               ←[m
                           ←[37m...←[m  ←[32m               ←[m
              ←[33mhsbox.core/←[1;33m-main←[m  ←[32m   core.clj: 59←[m
←[33mhsbox.indexer/←[1;33mset-indexed-path←[m  ←[32mindexer.clj: 32←[m
       ←[33mhsbox.util/←[1;33mpath-exists?←[m  ←[32m   util.clj: 10←[m
←[1;31mjava.lang.NullPointerException←[m: ←[3m←[m


```

**Comment by bugdone** [comment] 2015-11-09 09:48
Can you please tell me the directory path you have configured for the demos?
You can run hsbox with --no-indexer and look into Settings.

**Comment by reinZz** [comment] 2015-11-29 04:31
After retyping the demo directory path, the issue seems to be fixed. Thanks!!

**Comment by bugdone** [comment] 2016-05-21 19:08
Closing because there's no reproduction steps.

**Closed by bugdone** 2016-05-21 19:08 UTC
Labels: bug
