### ISSUE TITLE
Demo playback not working

### ISSUE THREAD

**Issue by caleywoods** [bugdone/headshotbox#171] opened 2016-07-05 01:26 UTC
After updating to .14 (from .12) demo playback no longer works for me. I have VDM scripting enabled in the settings with no config listed to execute. I've tried turning VDM scripting off and it had no effect on the demo working.

It doesn't matter if I'm trying to view a whole demo, highlights, or a single round either from a search or created demo note. These are all VALVe MM demos and I've tried Cache, Dust2, and Inferno.

[Here](https://gist.github.com/caleywoods/0ad7b58903c9cae5d0aa44925133302b) is the entire output from my console when the game launches. It also seems to "flash", the game loads, screen goes blank like it's going to play the demo, and then comes back to the menu without playing.

Edit: "kill CSGO if running before playing a demo" is checked, I noticed that when having CS:GO open and then trying to play the demo it correctly closes the game but fails to re-launch it and try and play the demo. Unchecking this option and leaving CS open also fails to play the demo. I think this may be related to #167 - how can I run that code early before .15 releases? I tried Chrome and IE and neither of those will - I will test firefox.

**Comment by caleywoods** [comment] 2016-07-05 01:37
Firefox appears to work correctly (as the fix for #167 states) - Currently Chrome and IE (shudders) remain broken.

**Comment by bugdone** [comment] 2016-07-05 05:44
This seems to be a duplicate of #167 
Building the code from source is probably hard (especially on windows) if you have no experience with c++ / clojure.

**Comment by bugdone** [comment] 2016-07-05 14:14
Hopefully the instructions in README.md are enough.
You can skip building demoinfogo and use the 0.14 binary.

**Comment by caleywoods** [comment] 2016-07-05 14:15
I'll give a try in a bit. Thanks

**Closed** 2016-07-12 19:27 UTC
