### ISSUE TITLE
DEMOs aren't starting when they are saved on a NAS

### ISSUE THREAD

**Issue by pAelish** [bugdone/headshotbox#146] opened 2016-03-25 07:42 UTC
My Demos are saved on a NAS (local storage is limited), the Share (r/w) is permanently mounted in Win7 (64bit) Explorer, Headshotbox can fetch and 'analyze' any Demo without any visible problems. 

While CS:GO is already running I am unable to run any Demos from Headshotbox. I have to shut down CS:GO frist and then start a Demo from Headshotbox CS.GO is immediatly loading up again and then  the selected Demo is loading right away.

**Comment by bugdone** [comment] 2016-03-25 10:05
Duplicate of #17

**Closed by bugdone** 2016-03-25 10:05 UTC
