### ISSUE TITLE
misscount of kills

### ISSUE THREAD

**Issue by semencmoz** [bugdone/headshotbox#75] opened 2015-09-08 06:55 UTC
i guess one of mine triple kills didn't made to hsbox scores
demo link steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-Q5dxk-BesGv-Sm6NF-PFcop-3De4D
![2](https://cloud.githubusercontent.com/assets/7286377/9728309/a7ca887c-560f-11e5-9bac-428e298bdc72.JPG)
![1](https://cloud.githubusercontent.com/assets/7286377/9728308/a7c84918-560f-11e5-8a80-d4b46e9d54b0.JPG)

**Comment by semencmoz** [comment] 2015-09-08 06:58
round 10 is missing

**Comment by bugdone** [comment] 2015-09-15 20:55
the link has expired :(

**Comment by semencmoz** [comment] 2015-09-16 04:48
https://drive.google.com/file/d/0BwnRDyFZ4le1VTBmZ0Z2aXJYNGs/view?usp=sharing
here is a google disk link. should work.

**Comment by bugdone** [comment] 2015-09-16 05:40
duplicate of #60

**Closed by bugdone** 2015-09-16 05:40 UTC
Labels: bug
