### ISSUE TITLE
Match result wrong in HSB

### ISSUE THREAD

**Issue by mschmitt** [bugdone/headshotbox#91] opened 2015-11-15 21:44 UTC
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-GacKW-zbK3e-HLA7c-3t4tE-J9tvE

This match was a tie, but HSB counts it as a 15-14 win for my team. Not sure what more I shall say. :-)

**Comment by bugdone** [comment] 2015-11-15 21:52
duplicate of #60

**Closed by bugdone** 2015-11-15 21:52 UTC
