### ISSUE TITLE
Suggestion: Show matches with banned players

### ISSUE THREAD

**Issue by TimHi** [bugdone/headshotbox#64] opened 2015-06-28 12:10 UTC
I really like the feeling of justice when one of my enemys gets banned and watching the demo afterwards sadly its hard to find the right one, it would be really cool to have an option to sort matches with banned people in them i guess this could be possible since you already show vac bans? 

If its too much to ask for i'm sorry just had that idea in mind

**Comment by bugdone** [comment] 2015-06-29 08:56
This was previously suggested (albeit in different forms) in #48 and #51 
I'll close this as a duplicate of #51 
I will do it btw, but there are some bugs I need to fix first.

**Closed by bugdone** 2015-06-29 08:56 UTC
