### ISSUE TITLE
Cache demos

### ISSUE THREAD

**Issue by TheTkeck** [bugdone/headshotbox#169] opened 2016-06-30 17:07 UTC
It would be nice if after the demos are parsed they could be cached. After awhile these 50-100mb demos do take up room. I don't use headshot box to replay demos only to keep track of stats so the ability to cache all the demos would be great.

**Comment by bugdone** [comment] 2016-07-11 10:34
duplicate of #173

**Closed by bugdone** 2016-07-11 10:34 UTC
